apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: DOCKER_REGISTRY/node:BUILD_NUMBER
        ports:
          - name: node-port
            containerPort: 4000
